import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { name, email, phone, purpose, message } = body as {
      name: string;
      email: string;
      phone?: string;
      purpose?: string;
      message: string;
    };

    if (!name || !email || !message) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Configure transporter (Gmail SMTP example)
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // 1. Send mail to company
    await transporter.sendMail({
      from: `"User Form" <${process.env.SMTP_USER}>`,
      to: 'contact@trangla.com', // replace with your company email
      subject: 'New User Form Submission - Trangla',
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; background-color: #f9fafb; padding: 32px;">
            <div style="max-width: 640px; margin: auto; background: #ffffff; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); overflow: hidden;">

            <!-- Header -->
            <div style="background: linear-gradient(90deg, #16a34a, #15803d); padding: 24px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">
                📩 New User Request Received
                </h1>
            </div>

            <!-- Body -->
            <div style="padding: 32px; color: #374151; font-size: 16px; line-height: 1.6;">
                <p style="margin: 0 0 16px;">
                A new user has submitted a request via the Trangla form. Here are the details:
                </p>

                <!-- Details Card -->
                <div style="background-color: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
                <p style="margin: 0 0 8px;"><b>👤 Name:</b> ${name}</p>
                <p style="margin: 0 0 8px;"><b>📧 Email:</b> ${email}</p>
                <p style="margin: 0 0 8px;"><b>📞 Phone:</b> ${phone || 'Not provided'}</p>
                <p style="margin: 0 0 8px;"><b>🎯 Purpose:</b> ${purpose || 'Not provided'}</p>
                <p style="margin: 0;"><b>📝 Message:</b> ${message}</p>
                </div>

                <p style="margin: 0 0 16px;">
                Please review the request and follow up as necessary.
                </p>

                <!-- Call to Action -->
                <div style="text-align: center; margin: 32px 0;">
                <a href="mailto:${email}" 
                    style="background: #16a34a; color: #ffffff; padding: 12px 24px; font-size: 16px; border-radius: 6px; text-decoration: none; font-weight: 500; display: inline-block;">
                    Reply to User
                </a>
                </div>
            </div>

            <!-- Footer -->
            <div style="background-color: #f9fafb; text-align: center; padding: 20px; font-size: 13px; color: #6b7280; border-top: 1px solid #e5e7eb;">
                <p style="margin: 4px 0;">This notification was automatically generated by Trangla Form System.</p>
            </div>
            </div>
        </div>
        `,
    });

    // 2. Send confirmation mail to user
    await transporter.sendMail({
      from: `"Trangla" <${process.env.SMTP_USER}>`,
      to: email,
      subject: 'Your Request Has Been Received – Trangla',
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; background-color: #f9fafb; padding: 32px;">
            <div style="max-width: 640px; margin: auto; background: #ffffff; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); overflow: hidden;">

            <!-- Header -->
            <div style="background: linear-gradient(90deg, #2563eb, #1d4ed8); padding: 24px; text-align: center;">
                <img src="./trangla-logo.png" alt="" style="height: 60px; margin-bottom: 12px;" />
                <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">
                We’ve Received Your Request
                </h1>
            </div>

            <!-- Body -->
            <div style="padding: 32px; color: #374151; font-size: 16px; line-height: 1.6;">
                <p style="margin: 0 0 16px;">Hello <b>${name}</b>,</p>
                <p style="margin: 0 0 24px;">
                Thank you for reaching out to <b>Trangla</b>. Your request has been successfully received and logged in our system.  
                Here are the details you submitted:
                </p>

                <!-- Details Card -->
                <div style="background-color: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
                <p style="margin: 0 0 8px;"><b>📞 Phone:</b> ${phone || 'Not provided'}</p>
                <p style="margin: 0 0 8px;"><b>🎯 Purpose:</b> ${purpose || 'Not provided'}</p>
                <p style="margin: 0;"><b>📝 Message:</b> ${message}</p>
                </div>

                <p style="margin: 0 0 24px;">
                Our support team will carefully review your request and get back to you as soon as possible.
                </p>

                <!-- Call to Action -->
                <div style="text-align: center; margin: 32px 0;">
                <a href="https://yourwebsite.com" 
                    style="background: #2563eb; color: #ffffff; padding: 12px 24px; font-size: 16px; border-radius: 6px; text-decoration: none; font-weight: 500; display: inline-block;">
                    Visit Trangla Website
                </a>
                </div>

                <p style="margin: 0;">Warm regards,</p>
                <p style="margin: 0;"><b>The Trangla Team</b></p>
            </div>

            <!-- Footer -->
            <div style="background-color: #f9fafb; text-align: center; padding: 20px; font-size: 13px; color: #6b7280; border-top: 1px solid #e5e7eb;">
                <p style="margin: 4px 0;">&copy; ${new Date().getFullYear()} Trangla. All rights reserved.</p>
                <p style="margin: 4px 0;">
                <a href="https://yourwebsite.com/privacy" style="color: #2563eb; text-decoration: none;">Privacy Policy</a> • 
                <a href="https://yourwebsite.com/contact" style="color: #2563eb; text-decoration: none;">Contact Support</a>
                </p>
            </div>
            </div>
        </div>
        `,
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
  }
}
